[package]
name = "mapstick"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.5"
tiny-skia = "0.11.4"
winit = "0.30.9"
winit_input_helper = "0.15"
pixels = "0.15.0"

[build-dependencies]
prost-build = "0.13.5"
